### ISSUE TITLE
[Suggestion] - SSRF - netdoc:// wrapper

### ISSUE THREAD

**Issue by ddocteur** [swisskyrepo/PayloadsAllTheThings#104]
This wrapper is useful when encountering an SSRF (Java only), especially if the SSRF struggles retrieving files having new line character(s).

https://www.kieranclaessens.be/cscbe-web-2018.html (Chapter One)

**Comment by swisskyrepo** [comment]
Nice finding 👍  , I've added it in https://github.com/swisskyrepo/PayloadsAllTheThings/commit/8eae039a28a14e867920b8317f4c4801af703860
