### ISSUE TITLE
/Server Side Template Injection/intruder payload lists are not template injection payloads.

### ISSUE THREAD

**Issue by BraveHelyx** [swisskyrepo/PayloadsAllTheThings#126]
The two files in `/Server Side Template Injection/Intruder` (`JHADDIX_SSI_injection.txt`, `ssi_quick.txt`) are incorrectly categorised as Server Side Template Injection payloads when they are in fact Server Side Includes Injection payloads. Furthermore, the two files in `/Server Side Template Injection/Files` (`SSRF_expect.svg`, `SSRF_url.svg`) appear to be files related to Server Side Request Forgery.

Proof:
* [JHADDIX_SSI_injection.txt](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Server%20Side%20Template%20Injection/Intruder/JHADDIX_SSI_Injection.txt)
* [ssi_quick.txt](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Server%20Side%20Template%20Injection/Intruder/ssi_quick.txt)
* [SSRF_expect.svg](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Server%20Side%20Template%20Injection/Files/SSRF_expect.svg)
* [SSRF_url.svg](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Server%20Side%20Template%20Injection/Files/SSRF_url.svg)

The README.md details correct information and sample payloads for testing SSTI for a variety of different templating engines. Would it be possible to push a commit replacing these files with relevant SSTI payloads?

**Comment by swisskyrepo** [comment]
Fixed in https://github.com/swisskyrepo/PayloadsAllTheThings/commit/95fed140ecdd652309fc312c04a18f1c3b42142b
