### ISSUE TITLE
PayloadsAllTheThings/File Inclusion/Intruders/Logs-files.txt is missing

### ISSUE THREAD

**Issue by mobrine-mob** [swisskyrepo/PayloadsAllTheThings#141]
PayloadsAllTheThings/File Inclusion/Intruders/Logs-files.txt doesn't have any log file

**Comment by pyaillet** [comment]
I would be glad to take on this issue, but I fear files there would overlap with [1](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/File%20Inclusion/Intruders/List_Of_File_To_Include.txt), [2](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/File%20Inclusion/Intruders/List_Of_File_To_Include_NullByteAdded.txt), and maybe other...

Should the file names be moved in `Logs-files.txt` or duplicated ?

**Comment by swisskyrepo** [comment]
The file is no longer useful since we have the two others mentionned by @pyaillet 
I have deleted it ;)
