### ISSUE TITLE
Koadic-hashdump_sam issue

### ISSUE THREAD

**Issue by jeffinm** [swisskyrepo/PayloadsAllTheThings#153]
Hi,
When i am using hashdump_sam implant, i am getting the below error any idea why?.

[-] SAM hashes extraction failed: local variable 'encNTHash' referenced before assignment

-----
(koadic: imp/gat/hashdump_sam)# run
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) created.
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) received SAM hive (50744 bytes)
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) received SECURITY hive (39484 bytes)
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) received SYSTEM hive (12491836 bytes)
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) decoded SAM hive (/tmp/SAM.10.0.2.6.cb829d3635394453937646ce788240fa)
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) decoded SECURITY hive (/tmp/SECURITY.10.0.2.6.8c0d73ba7d6149e180325394e21bebf9)
[*] Zombie 1: Job 20 (implant/gather/hashdump_sam) decoded SYSTEM hive (/tmp/SYSTEM.10.0.2.6.4410293a697b437fae605678660c6f8f)
[+] Zombie 1: Job 20 (implant/gather/hashdump_sam) completed.
Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies

[*] Target system bootKey: 0xcdf5a894ed64473fef79ccc0d40cb49b
[*] Dumping local SAM hashes (uid:rid:lmhash:nthash)

[-] SAM hashes extraction failed: local variable 'encNTHash' referenced before assignment

[*] Dumping cached domain logon information (uid:encryptedHash:longDomain:domain)
[*] Dumping LSA Secrets
[*] DPAPI_SYSTEM 
 0000   01 00 00 00 C7 F3 7C 9B  D3 E5 C8 71 14 07 DE 11   ......|....q....
 0010   3B B7 98 AD D1 11 FD 5F  69 09 C3 28 D2 2A 8F 0B   ;......_i..(.*..
 0020   7C 65 24 DF D0 D7 7B 9B  F6 12 25 11               |e$...{...%.
DPAPI_SYSTEM:01000000c7f37c9bd3e5c8711407de113bb798add111fd5f6909c328d22a8f0b7c

**Comment by swisskyrepo** [comment]
Please refer to the original repository https://github.com/zerosum0x0/koadic for issues related to the tool
