### ISSUE TITLE
add section with code snippets, that protect against all listed payloads

### ISSUE THREAD

**Issue by rubo77** [swisskyrepo/PayloadsAllTheThings#168]
It would be great if we add solution to each section that protects your code/server.
For example a PHP script that sanitises request strings against all attacks

**Comment by bsysop** [comment]
Would be "ProtectAllTheThings" :)

**Comment by pS3ud0RAnD0m** [comment]
ya, that's a slippery slope. i think the current scope of this repo is perfect.
