### ISSUE TITLE
SQLi authentication bypass by spidersec

### ISSUE THREAD

**Issue by 0xShin** [swisskyrepo/PayloadsAllTheThings#185]
Hello, I would like to suggest this authentication bypass that was shared by spidersec on Twitter which is.
`'--'`
`"--"`

[TwitterPost](https://twitter.com/SpiderSec/status/1251793902996279297)

**Comment by swisskyrepo** [comment]
Done in https://github.com/swisskyrepo/PayloadsAllTheThings/commit/eaac0e748eabbf25d63a88d2d8c7e69f8b6677c0, thx
