### ISSUE TITLE
Can i make a blog website for this repo?

### ISSUE THREAD

**Issue by Zxce3** [swisskyrepo/PayloadsAllTheThings#363]
Can i make a blog website for this repo? @swisskyrepo

**Comment by clem9669** [comment]
Send us the link 😉

**Comment by Zxce3** [comment]
> Send us the link 😉

https://payloadsallthethings.web.app

not finished and I'm a little lazy👍
It's really just a matter of adding and adjusting the categories and post tags.

**Comment by PinkDev1** [comment]
@Zxce3 it looks awesome! thanks for your effort :)

**Comment by Zxce3** [comment]
@PinkDev1 so what do you think do I continue or not?

**Comment by fgeek** [comment]
@Zxce3 yes, please do

**Comment by Zxce3** [comment]
[https://github.com/Zxce3/PayloadsAllTheThings/tree/web](https://github.com/Zxce3/PayloadsAllTheThings/tree/web)
