### ISSUE TITLE
Git Clone Failure on Windows 10

### ISSUE THREAD

**Issue by HustleSec** [swisskyrepo/PayloadsAllTheThings#368]
When I attempt to git clone the repository on my Windows 10 device, I get this error:

Cloning into 'PayloadsAllTheThings'...
remote: Enumerating objects: 5197, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 5197 (delta 57), reused 91 (delta 47), pack-reused 5074R
Receiving objects: 100% (5197/5197), 10.78 MiB | 7.14 MiB/s, done.
Resolving deltas: 100% (2972/2972), done.
**error: invalid path 'Server Side Request Forgery/Images/Parser & Curl < 7.54.png'
fatal: unable to checkout working tree**
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

During the process, it makes an empty PayloadsAllTheThings folder in the specified path and quits. Please help!

**Comment by clem9669** [comment]
Hey @HustleSec ,

Windows is complaining about illegal path. 
This blog is relevant for this problem: https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/

A workaround is to download the zip file.
Cheers
