### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jopraveen** [swisskyrepo/PayloadsAllTheThings#369]
A little typo in Subdomains Enumeration.md

Using HostileSubBruteForcer

```
git clone https://github.com/nahamsec/HostileSubBruteforcer
chmox +x sub_brute.rb
./sub_brute.rb
```

Here `chmox` change it to `chmod`

I don't think this is an issue, but it helps :)

**Comment by leongross** [comment]
issue resolved !#383, please close issue.
