### ISSUE TITLE
Python 3.8.6

### ISSUE THREAD

**Issue by odaialhmwi1996** [swisskyrepo/PayloadsAllTheThings#373]
$ uname -m
armv7l
$ pkg uninstall python
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  python
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 46.8 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 13912 files and directories currently installed.)
Removing python (3.8.0-1) ...
Uninstalling python modules...
Deleting remaining files from site-packages...
$ cd /storage/emulated/0/Download/Python3.8
$ ls
Python3.8                    python-tkinter_3.8.6_arm.deb
python-static_3.8.6_arm.deb  python_3.8.6_arm.deb
$ dpkg -i ./python_3.8.6_arm.deb
Selecting previously unselected package python.
(Reading database ... 11133 files and directories currently installed.)
Preparing to unpack ./python_3.8.6_arm.deb ...
Unpacking python (3.8.6) ...
Setting up python (3.8.6) ...
Setting up pip...
WARNING: linker: /data/data/com.termux/files/usr/bin/python3: unused DT entry: type 0x6ffffef5 arg 0x3a4
WARNING: linker: /data/data/com.termux/files/usr/bin/python3: unused DT entry: type 0x1d arg 0xae
WARNING: linker: /data/data/com.termux/files/usr/bin/python3: unused DT entry: type 0x6ffffffe arg 0x44c
WARNING: linker: /data/data/com.termux/files/usr/bin/python3: unused DT entry: type 0x6fffffff arg 0x1
WARNING: linker: libpython3.8.so.1.0: unused DT entry: type 0x6ffffef5 arg 0x13900
WARNING: linker: libpython3.8.so.1.0: unused DT entry: type 0x1d arg 0xa79f
WARNING: linker: libpython3.8.so.1.0: unused DT entry: type 0x6ffffffe arg 0x1c60c
WARNING: linker: libpython3.8.so.1.0: unused DT entry: type 0x6fffffff arg 0x3
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__register_atfork" referenced by "libpython3.8.so.1.0"...
$

**Comment by JulianVolodia** [comment]
hey, but actually... why it was posted here? ☺️ 

cu
