### ISSUE TITLE
Include FFMPEG INJECTION

### ISSUE THREAD

**Issue by xlocux** [swisskyrepo/PayloadsAllTheThings#5]
Hi, 
thanks for this repo is very usefull! 
You should also add the ffmpeg injection, looks at the links below for more info:

https://hackerone.com/reports/242831

https://docs.google.com/presentation/d/1yqWy_aE3dQNXAhW8kxMxRqtP7qMHaIfMzUDpEqFneos/edit#slide=id.p

cheers

**Comment by swisskyrepo** [comment]
I'm glad you like it :)
You can find the FFMPEG injection via HLS here : https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Upload%20insecure%20files/Ffmpeg%20HLS

Best regards ;)

**Comment by abdilahrf** [comment]
Cool :+1:

**Comment by Georger0ot** [comment]
<3 <3 thanks people
