### ISSUE TITLE
EoP - Unquoted Service Paths

### ISSUE THREAD

**Issue by PowerPress** [swisskyrepo/PayloadsAllTheThings#59]
Following command fails
gwmi -class Win32_Service -Property Name, DisplayName, PathName, StartMode | Where {$_.StartMode -eq "Auto" -and $_.PathName -notlike "C:\Windows*" -and $_.PathName -notlike '"*'} | select PathName,DisplayName,Name

'gwmi' is not recognized as an internal or external command, operable program or batch file.

If modified to the following:
wmic -class Win32_Service -Property Name, DisplayName, PathName, StartMode | Where {$_.StartMode -eq "Auto" -and $_.PathName -notlike "C:\Windows*" -and $_.PathName -notlike '"*'} | select PathName,DisplayName,Name

Fails with following error: 
ERROR: Invalid pattern is specified in "path:pattern".
Invalid Global Switch.

**Comment by swisskyrepo** [comment]
gwmi is a Powershell alias for [Get-WmiObject](https://ss64.com/ps/get-wmiobject.html)
