### ISSUE TITLE
What licence?

### ISSUE THREAD

**Issue by g0tmi1k** [swisskyrepo/PayloadsAllTheThings#69]
What licence does this use?

**Comment by yehgdotnet** [comment]
Since materials posted here are from public domains, this repo can't have license,  I guess. Please correct me if I'm wrong.

**Comment by X0R1972** [comment]
exactly what licence are we talking about ???

**Comment by swisskyrepo** [comment]
Since it's a collection of many payloads grabbed around multiple sources, I think MIT is good enough. (SecLists project is using the same license)
The license was added in the latest commit.
