### ISSUE TITLE
SSRF payloads for containers running on AWS ECS

### ISSUE THREAD

**Issue by wu4f** [swisskyrepo/PayloadsAllTheThings#84]
Would be good to add to the list...

169.254.170.2/v2/credentials/GUID

See Level 3 of flaws2.cloud

**Comment by swisskyrepo** [comment]
Done and available at [method-for-container-service-fargate](https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Cloud%20-%20AWS%20Pentest.md#method-for-container-service-fargate)
