### ISSUE TITLE
jsonp endpt https://www.google.com/complete/search?client=chrome&q=hello&callback=alert

### ISSUE THREAD

**Issue by evandrix** [swisskyrepo/PayloadsAllTheThings#90]
writeup https://corb3nik.github.io/blog/ins-hack-2019/bypasses-everywhere

**Comment by ajdumanhug** [comment]
The technique on this writeup is already in the list of XSS Payloads (Please [see](https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/XSS%20Injection#bypass-csp-using-jsonp-from-google-trick-by-apfeifer27))

But admin can still add this as a resource.

**Comment by abdilahrf** [comment]
This list have more endpoint, if another one got blacklisted https://github.com/zigoo0/JSONBee/blob/master/jsonp.txt
